dist: trusty

jobs:
  language: node_js
  node_js:
    - "12"
  sudo: required
  services:
    -docker
  jobs:
    include:
      - stage: Test Stage
        before_scripts:
        - npm install
        script:
          - npm test
        after_success:
          - echo "Test Success!"
      - stage: build bocker image
        script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t myportfolio:$TRAVIS_BUILD_NUMBER .
          - docker tag myportfolio:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/myrepo
          - docker push $DOCKER_USERNAME/myrepo:latest