dist: trusty

jobs:
  include:
    - stage: build bocker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t myrepo:$TRAVIS_BUILD_NUMBER .
        - docker tag myrepo:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/myrepo
        - docker push $DOCKER_USERNAME/myrepo:latestS